#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path


def command_exists(name: str) -> bool:
    return shutil.which(name) is not None


def resolve_erp_dir(devkit_dir: Path, positional: str | None) -> Path | None:
    if positional:
        return Path(positional).expanduser()

    env_val = os.environ.get("ODOO_REPO_PATH")
    if env_val:
        return Path(env_val).expanduser()

    sibling = devkit_dir.parent / "erp"
    if sibling.exists():
        return sibling

    cwd = Path.cwd()
    if (cwd / "docker-compose.yml").exists():
        return cwd

    return None


def safe_symlink(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.is_symlink():
        dst.unlink()
    elif dst.exists() and not dst.is_dir():
        dst.unlink()
    elif dst.exists() and dst.is_dir():
        # keep existing real dirs untouched
        return
    dst.symlink_to(src)


def ensure_local_exclude(erp_dir: Path) -> str:
    exclude_file = erp_dir / ".git" / "info" / "exclude"
    exclude_file.parent.mkdir(parents=True, exist_ok=True)
    existing = exclude_file.read_text(encoding="utf-8") if exclude_file.exists() else ""
    if any(line.strip() == ".pi/" for line in existing.splitlines()):
        return f"Local git exclude already contains '.pi/': {exclude_file}"
    with exclude_file.open("a", encoding="utf-8") as f:
        f.write("\n# local pi files\n.pi/\n")
    return f"Added local git exclude '.pi/' to: {exclude_file}"


def ensure_envrc(devkit_dir: Path) -> list[str]:
    messages: list[str] = []
    envrc = devkit_dir / ".envrc"
    gitignore = devkit_dir / ".gitignore"
    venv_dir = devkit_dir / ".venv"

    envrc_content = """# Odoo Devkit recommended environment (direnv + venv)
export ODOO_DEVKIT_ROOT=\"$(pwd)\"
# Legacy compatibility variable
export ERP_DEVKIT_ROOT=\"$ODOO_DEVKIT_ROOT\"

if [ ! -d .venv ]; then
  python3 -m venv .venv
fi

source .venv/bin/activate
export PATH=\"$ODOO_DEVKIT_ROOT/commands:$PATH\"
"""

    if not envrc.exists():
        envrc.write_text(envrc_content, encoding="utf-8")
        messages.append(f"Created {envrc}")
    else:
        messages.append(f"Kept existing {envrc}")

    ignore_lines = gitignore.read_text(encoding="utf-8").splitlines() if gitignore.exists() else []
    changed = False
    for line in [".venv/", ".direnv/"]:
        if line not in ignore_lines:
            ignore_lines.append(line)
            changed = True
    if changed or not gitignore.exists():
        gitignore.write_text("\n".join(ignore_lines).strip() + "\n", encoding="utf-8")
        messages.append(f"Updated {gitignore} with .venv/.direnv ignores")

    if not venv_dir.exists():
        subprocess.run([sys.executable, "-m", "venv", str(venv_dir)], check=True)
        messages.append(f"Created virtualenv: {venv_dir}")
    else:
        messages.append(f"Virtualenv already present: {venv_dir}")

    if command_exists("direnv"):
        messages.append("direnv detected. Run: direnv allow")
    else:
        messages.append("direnv not found. Install direnv for recommended setup, then run: direnv allow")

    return messages


def install_browser_tools(devkit_dir: Path) -> list[str]:
    messages: list[str] = []
    bt_dir = devkit_dir / "skills" / "browser-tools" / "browser-tools"

    if not bt_dir.exists():
        return [f"Browser tools directory missing: {bt_dir}"]

    missing = [tool for tool in ("node", "npm") if not command_exists(tool)]
    if missing:
        return [f"Browser tools setup skipped: missing dependencies: {', '.join(missing)}"]

    messages.append(f"Running npm install in {bt_dir} ...")
    subprocess.run(["npm", "install"], cwd=bt_dir, check=True)
    messages.append("Browser tools npm dependencies installed.")

    chromium_path = Path("/Applications/Chromium.app/Contents/MacOS/Chromium")
    if not chromium_path.exists():
        messages.append(
            "Note: Chromium app not found at /Applications/Chromium.app/Contents/MacOS/Chromium. "
            "Update browser-start.js or install Chromium there."
        )

    return messages


def write_local_agent_notes(erp_dir: Path, devkit_dir: Path) -> Path:
    notes_path = erp_dir / ".pi" / "DEVKIT_AGENT_NOTES.md"
    content = f"""# Odoo Devkit Local Notes

<!-- managed-by: erp-devkit installer -->

This file is generated by `erp-devkit/bootstrap/install.py`.

## Shared Devkit Links

- Skills: `.pi/skills/shared-devkit`
- Commands: `.pi/tools/shared-devkit`
- Dev command: `.pi/tools/devkit`

## Quick Commands

```bash
./.pi/tools/devkit help
./.pi/tools/devkit up
./.pi/tools/devkit db
./.pi/tools/devkit shell
```

## Browser Skill Dependency

If using browser-based skills (`browser-tools`, `odoo-ui-check`, `odoo-ui-regression-check`), ensure browser-tools deps are installed:

```bash
{devkit_dir}/bootstrap/install.sh {erp_dir} --with-browser-tools --yes
```

## Notes

- This file is local support material; it does not modify `AGENTS.md`/`CLAUDE.md` automatically.
- If you want to reference it, add a short line in your preferred agent doc.
"""
    notes_path.parent.mkdir(parents=True, exist_ok=True)
    notes_path.write_text(content, encoding="utf-8")
    return notes_path


def print_agent_doc_guidance(erp_dir: Path, notes_path: Path) -> None:
    print("\n[agent docs]")
    print(f"- Wrote local include notes: {notes_path}")

    existing = [p for p in (erp_dir / "AGENTS.md", erp_dir / "CLAUDE.md") if p.exists()]
    if existing:
        print("- Existing agent docs detected:")
        for p in existing:
            print(f"  - {p}")
        print("- No automatic edits were applied (non-invasive by design).")
    else:
        print("- No AGENTS.md/CLAUDE.md found at repo root. That's okay.")

    print("- Optional copy/paste snippet:")
    print("""
## Local Devkit Notes (optional)
For local helper workflows, see `.pi/DEVKIT_AGENT_NOTES.md`.
""".strip())


def prompt_yes_no(question: str, default_yes: bool = True) -> bool:
    default = "Y/n" if default_yes else "y/N"
    while True:
        ans = input(f"{question} [{default}] ").strip().lower()
        if not ans:
            return default_yes
        if ans in {"y", "yes"}:
            return True
        if ans in {"n", "no"}:
            return False
        print("Please answer yes or no.")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Install Odoo devkit links and optional batteries-included setup."
    )
    parser.add_argument("project_repo_path", nargs="?", help="Path to Odoo project repo")
    parser.add_argument(
        "--add-local-exclude",
        action="store_true",
        help="Add '.pi/' to <erp>/.git/info/exclude (local-only)",
    )
    parser.add_argument(
        "--with-browser-tools",
        action="store_true",
        help="Install browser-tools npm dependencies",
    )
    parser.add_argument(
        "--without-browser-tools",
        action="store_true",
        help="Skip browser-tools npm dependencies",
    )
    parser.add_argument(
        "--without-envrc",
        action="store_true",
        help="Skip recommended .envrc/.venv bootstrap",
    )
    parser.add_argument(
        "--yes",
        action="store_true",
        help="Non-interactive mode (use recommended defaults)",
    )

    args = parser.parse_args()

    if args.with_browser_tools and args.without_browser_tools:
        print("Cannot combine --with-browser-tools and --without-browser-tools", file=sys.stderr)
        return 2

    devkit_dir = Path(__file__).resolve().parent.parent
    project_dir_raw = resolve_erp_dir(devkit_dir, args.project_repo_path)
    if not project_dir_raw:
        print("Could not resolve Odoo project repo path.", file=sys.stderr)
        parser.print_help()
        return 1

    erp_dir = project_dir_raw.expanduser().resolve()
    if not erp_dir.exists():
        print(f"Project repo path does not exist: {erp_dir}", file=sys.stderr)
        return 1
    if not (erp_dir / "docker-compose.yml").exists():
        print(f"Not an Odoo project repo (missing docker-compose.yml): {erp_dir}", file=sys.stderr)
        return 1

    interactive = sys.stdin.isatty() and not args.yes

    if args.with_browser_tools:
        enable_browser_tools = True
    elif args.without_browser_tools:
        enable_browser_tools = False
    elif interactive:
        enable_browser_tools = prompt_yes_no("Install browser-tools dependencies (npm install)?", default_yes=True)
    else:
        enable_browser_tools = True

    if args.without_envrc:
        enable_envrc = False
    elif interactive:
        enable_envrc = prompt_yes_no("Setup recommended direnv + .venv environment?", default_yes=True)
    else:
        enable_envrc = True

    # Core links
    (erp_dir / ".pi" / "skills").mkdir(parents=True, exist_ok=True)
    (erp_dir / ".pi" / "tools").mkdir(parents=True, exist_ok=True)

    safe_symlink(devkit_dir / "skills", erp_dir / ".pi" / "skills" / "shared-devkit")
    safe_symlink(devkit_dir / "commands", erp_dir / ".pi" / "tools" / "shared-devkit")

    devkit_cmd_link = erp_dir / ".pi" / "tools" / "devkit"
    if not devkit_cmd_link.exists():
        devkit_cmd_link.symlink_to(devkit_dir / "commands" / "dev")

    notes_path = write_local_agent_notes(erp_dir, devkit_dir)

    print(f"Installed devkit links into: {erp_dir}")
    print(f"  .pi/skills/shared-devkit -> {devkit_dir / 'skills'}")
    print(f"  .pi/tools/shared-devkit  -> {devkit_dir / 'commands'}")
    if devkit_cmd_link.is_symlink():
        print(f"  .pi/tools/devkit          -> {devkit_dir / 'commands' / 'dev'}")

    if args.add_local_exclude:
        print(ensure_local_exclude(erp_dir))
    else:
        print("Tip: rerun with --add-local-exclude to hide .pi from git status (local-only).")

    # Recommended env setup
    if enable_envrc:
        print("\n[env setup]")
        for m in ensure_envrc(devkit_dir):
            print(f"- {m}")
    else:
        print("\n[env setup] skipped (--without-envrc)")

    # Optional browser-tools batteries
    if enable_browser_tools:
        print("\n[browser-tools]")
        try:
            for m in install_browser_tools(devkit_dir):
                print(f"- {m}")
        except subprocess.CalledProcessError as e:
            print(f"- Browser tools setup failed with exit code {e.returncode}", file=sys.stderr)
            return e.returncode
    else:
        print("\n[browser-tools] skipped")

    print_agent_doc_guidance(erp_dir, notes_path)

    # Core dependency summary
    print("\n[dependency check]")
    for tool, required in [
        ("python3", True),
        ("docker", True),
        ("node", False),
        ("npm", False),
        ("direnv", False),
    ]:
        ok = command_exists(tool)
        status = "OK" if ok else ("MISSING (required)" if required else "MISSING (optional)")
        print(f"- {tool}: {status}")

    print("\nNext steps:")
    step = 1
    if enable_envrc and command_exists("direnv"):
        print(f"{step}) cd {devkit_dir} && direnv allow")
        step += 1
    print(f"{step}) {erp_dir}/.pi/tools/devkit help")
    step += 1
    print(f"{step}) {devkit_dir}/bootstrap/doctor.py {erp_dir}")
    step += 1
    print(f"{step}) If using browser skill: run browser-start.js via the skill instructions")
    step += 1
    print(f"{step}) For cleanup later: {devkit_dir}/bootstrap/uninstall.py {erp_dir}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
